version: '3.3'

services:
  web:
    image: brasty-group
    build: ./.docker/web
    volumes:
      - ./nevim/:/var/www/html/
      - ./.docker/web/sites-enabled:/etc/apache2/sites-enabled
      - ./.docker/web/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/web/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - type: bind
        source: ./.env
        target: /var/www/html/.env
    ports:
      - 80:80
      - 443:443
    environment:
      PHP_IDE_CONFIG: serverName=nevim.local
      DOCKER_DEV: 'true'
      APACHE_RUN_USER: "www-data"
      APACHE_RUN_GROUP: "www-data"

  database:
    image: postgres:14.1
    volumes:
      - ./.docker/database:/tmp
      - ondra-postgdata:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5435:5432

volumes:
  ondra-esdata:
  ondra-postgdata: